# Generated by Django 5.1.4 on 2025-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('legajo', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('email_personal', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_personal', models.CharField(max_length=25)),
                ('phone_emergency', models.CharField(max_length=25)),
                ('ffss', models.CharField(max_length=150)),
                ('destinos', models.TextField(blank=True, null=True)),
                ('weapon_assigned', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=10, null=True)),
                ('weapon_number', models.CharField(blank=True, max_length=50, null=True)),
                ('studies', models.TextField(blank=True, null=True)),
                ('certificaciones', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('efectivizacion_date', models.DateField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('privi_AD', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo_AD', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
