# Generated by Django 5.1.4 on 2025-03-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_miembro_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='ciudad_de_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='ciudadania',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Chile', 'Chile'), ('Paraguay', 'Paraguay'), ('Uruguay', 'Uruguay'), ('Otro', 'Otro')], default='Argentina', max_length=100),
        ),
        migrations.AddField(
            model_name='miembro',
            name='provincia_de_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
